<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BachKhoaToanThuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('bach_khoa_toan_thu')->truncate();

        DB::table('bach_khoa_toan_thu')->insert([
            [
                'tieu_de' => 'Anabolic Steroid (Steroid đồng hóa) là gì?',
                'chu_de' => 'Dược lý & Hormone',
                'anh_bia' => 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Steroid đồng hóa là các loại thuốc bắt chước tác dụng của hormone sinh dục nam testosterone trong cơ thể.',
                'noi_dung' => "Steroid đồng hóa (anabolic) là các loại thuốc dược lý bắt chước tác dụng của hormone sinh dục nam testosterone và dihydrotestosterone.\n\nSteroid đồng hóa làm tăng tốc độ tổng hợp protein trong tế bào, dẫn đến sự phì đại rõ rệt của mô cơ (toàn bộ quá trình này được gọi là đồng hóa), đó là lý do tại sao chúng được sử dụng rộng rãi trong thể hình.\n\nCơ chế hoạt động của steroid đồng hóa khác với hormone peptide: một khi vào máu, các phân tử steroid được phân phối khắp cơ thể, nơi chúng tương tác với các tế bào của cơ xương, tuyến bã nhờn, nang lông, một số vùng của não và một số tuyến nội tiết.\n\nSteroid đồng hóa tan trong chất béo, cho phép chúng xâm nhập vào màng tế bào, vốn được cấu tạo từ chất béo.\n\nBên trong tế bào, steroid đồng hóa tương tác (liên kết) với các thụ thể androgen trong nhân và tế bào chất. Các thụ thể androgen được kích hoạt sẽ truyền tín hiệu vào nhân tế bào, dẫn đến sự thay đổi biểu hiện gen hoặc kích hoạt các quá trình gửi tín hiệu đến các bộ phận khác của tế bào.\n\nĐiều này kích thích sự tổng hợp của tất cả các loại protein, bao gồm myosin và actin (các thành phần chính của cơ bắp), dẫn đến sự gia tăng sức mạnh và kích thước cơ bắp đáng kể.",
                'luot_xem' => 1240,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Bài tập khu cơ (Bài tập chuyên biệt / Isolation)',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Cách tác động trực tiếp vào các bó cơ nhỏ giúp hoàn thiện vẻ đẹp cân đối và khắc phục điểm yếu cơ thể.',
                'noi_dung' => "Bài tập khu cơ (isolation exercises) là những động tác chỉ tác động chủ yếu lên một nhóm cơ duy nhất và chuyển động qua một khớp (single-joint movement).\n\nLợi ích chính của bài tập khu cơ:\n1. Tập trung tối đa áp lực vào bó cơ mục tiêu mà không bị phân tán lực bởi các cơ hỗ trợ.\n2. Khắc phục sự mất cân bằng giữa hai bên cơ thể (trái - phải) hoặc giữa các bó cơ trong cùng một nhóm cơ lớn.\n3. Hỗ trợ phục hồi sau chấn thương một cách an toàn mà không gây áp lực lớn lên toàn bộ hệ thống thần kinh.\n\nVí dụ điển hình:\n- Bắp tay trước: Bicep Curls (cuốn tạ đơn/thanh tạ)\n- Cơ ngực: Pec Deck Fly / Cable Crossover\n- Cơ đùi: Leg Extension (đá đùi trước), Leg Curl (móc đùi sau).",
                'luot_xem' => 890,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Béo bụng: Nguyên nhân và cách giảm mỡ hiệu quả',
                'chu_de' => 'Dinh dưỡng & Giảm mỡ',
                'anh_bia' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiểu rõ sự khác biệt giữa mỡ dưới da và mỡ nội tạng để áp dụng chế độ tập luyện, dinh dưỡng khoa học.',
                'noi_dung' => "Mỡ bụng không chỉ ảnh hưởng đến thẩm mỹ mà còn là nguy cơ tiềm ẩn cho sức khỏe tim mạch và chuyển hóa.\n\nCó 2 loại mỡ bụng chính:\n1. Mỡ dưới da (Subcutaneous fat): Lớp mỡ nằm ngay dưới bề mặt da, có thể dùng tay véo được. Loại mỡ này ít gây nguy hiểm cho sức khỏe hơn nhưng khó giảm hơn.\n2. Mỡ nội tạng (Visceral fat): Lớp mỡ bao quanh các cơ quan nội tạng trong khoang bụng. Đây là loại mỡ nguy hiểm, liên quan trực tiếp đến bệnh tiểu đường type 2, gan nhiễm mỡ và tim mạch.\n\nChiến lược giảm mỡ bụng bền vững:\n- Tạo thâm hụt calo hợp lý (300 - 500 kcal/ngày).\n- Ưu tiên chế độ ăn giàu protein để bảo toàn cơ bắp và duy trì cảm giác no lâu.\n- Kết hợp tập kháng lực (Strength training) với cardio cường độ vừa phải hoặc HIIT.\n- Quản lý căng thẳng và ngủ đủ giấc (7-8 tiếng/đêm) để kiểm soát hormone Cortisol.",
                'luot_xem' => 2150,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Bạn thuộc tạng người nào: Ectomorph (gầy), Mesomorph (cơ bắp), Endomorph (béo)?',
                'chu_de' => 'Tạng người & Thể chất',
                'anh_bia' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Nhận biết đặc điểm thể trạng di truyền của bạn để tối ưu hóa giáo án tập và thực đơn ăn uống.',
                'noi_dung' => "Khái niệm 3 tạng người (Somatotypes) do Tiến sĩ William Sheldon phát triển giúp phân loại thể trạng con người:\n\n1. Ectomorph (Tạng người gầy khó tăng cân):\n- Đặc điểm: Khung xương nhỏ, khớp nhỏ, vai hẹp, trao đổi chất cực nhanh, khó tích trữ cả mỡ lẫn cơ.\n- Lời khuyên: Cần ăn dư calo nhiều, bổ sung carb phức tạp và hạn chế cardio quá mức.\n\n2. Mesomorph (Tạng người cơ bắp tự nhiên):\n- Đặc điểm: Khung xương vừa đến lớn, vai rộng, eo thon (thân hình chữ V), dễ tăng cơ và dễ kiểm soát lượng mỡ.\n- Lời khuyên: Phù hợp với hầu hết các hình thức tập luyện nặng và chế độ ăn cân bằng.\n\n3. Endomorph (Tạng người dễ tích mỡ):\n- Đặc điểm: Khung xương to, hông rộng, trao đổi chất chậm, dễ tăng cân (cả cơ và mỡ) nhưng khó giảm cân.\n- Lời khuyên: Cần kiểm soát lượng carb chặt chẽ, tăng cường protein và bổ sung bài tập cardio thường xuyên.",
                'luot_xem' => 3420,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Carbohydrate đơn giản và carbohydrate phức tạp là gì?',
                'chu_de' => 'Dinh dưỡng',
                'anh_bia' => 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Phân biệt 2 loại đường bột để nạp năng lượng thông minh trước, trong và sau các buổi tập nặng.',
                'noi_dung' => "Carbohydrate (tinh bột/đường) là nguồn năng lượng chính cho cơ bắp và não bộ khi hoạt động thể chất.\n\n1. Carbohydrate đơn giản (Simple Carbs):\n- Cấu trúc: Chuỗi phân tử đường ngắn (glucose, fructose, sucrose).\n- Đặc tính: Hấp thu vào máu rất nhanh, làm tăng vọt đường huyết và giải phóng Insulin nhanh chóng.\n- Thực phẩm: Trái cây ngọt, mật ong, bánh kẹo, nước ngọt, đường tinh luyện.\n- Thời điểm dùng: Rất tốt khi cần năng lượng gấp ngay trước buổi tập hoặc nạp nhanh glycogen ngay sau buổi tập nặng.\n\n2. Carbohydrate phức tạp (Complex Carbs):\n- Cấu trúc: Chuỗi polysaccharide dài gồm nhiều phân tử đường liên kết và chứa nhiều chất xơ.\n- Đặc tính: Tiêu hóa và giải phóng năng lượng từ từ, duy trì mức đường huyết ổn định lâu dài.\n- Thực phẩm: Gạo lứt, yến mạch, khoai lang, bánh mì nguyên cám, các loại đậu.\n- Thời điểm dùng: Thích hợp cho các bữa ăn chính trong ngày để duy trì năng lượng bền bỉ.",
                'luot_xem' => 1560,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cellulite (Sần vỏ cam): Cơ chế và giải pháp khắc phục',
                'chu_de' => 'Sức khỏe & Làm đẹp',
                'anh_bia' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiện tượng sần vỏ cam ở đùi và mông xuất phát từ đâu và làm thế nào để làm săn chắc da hiệu quả.',
                'noi_dung' => "Cellulite là tình trạng các tế bào mỡ dưới da đẩy trồi lên xuyên qua các dải mô liên kết (dải collagen dạng lưới), tạo nên bề mặt da sần sùi giống như vỏ quả cam.\n\nHiện tượng này phổ biến ở 80-90% phụ nữ trưởng thành do cấu trúc sợi mô liên kết dạng thẳng đứng ở nữ giới (khác với dạng mạng chéo đan xen ở nam giới).\n\nCác biện pháp cải thiện thực chứng:\n- Tập kháng lực phát triển các nhóm cơ bên dưới (cơ đùi, cơ mông) để làm căng bề mặt da.\n- Giảm tỷ lệ mỡ cơ thể tổng thể (Body fat percentage).\n- Uống đủ nước (2 - 3 lít/ngày) và bổ sung vitamin C để tăng cường tổng hợp collagen tự nhiên.",
                'luot_xem' => 1120,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Creatine Monohydrate: Tác dụng, liều dùng và cách nạp hiệu quả nhất',
                'chu_de' => 'Thực phẩm bổ sung',
                'anh_bia' => 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Creatine là thực phẩm bổ sung được nghiên cứu khoa học kỹ lưỡng nhất giúp tăng sức mạnh và phì đại tế bào cơ.',
                'noi_dung' => "Creatine là một hợp chất tự nhiên có trong các tế bào cơ, được tạo thành từ ba axit amin: arginine, glycine và methionine.\n\nCơ chế hoạt động:\nKhi bạn nâng tạ nặng hoặc bùng nổ sức mạnh, cơ thể sử dụng năng lượng ATP (Adenosine Triphosphate). ATP bị phân giải thành ADP và mất năng lượng. Creatine phosphate đóng vai trò tặng nhóm phosphate để tái tạo ADP thành ATP ngay lập tức, giúp bạn nâng được thêm 1-2 reps ở mức tạ nặng.\n\nLợi ích chính:\n1. Tăng sức mạnh tức thời trong các bài tập compound (Squat, Bench, Deadlift).\n2. Hút nước vào tế bào cơ (Intracellular hydration), tạo môi trường đồng hóa lý tưởng kích thích cơ bắp phát triển.\n3. Hỗ trợ chức năng não bộ và trí nhớ.\n\nCách dùng chuẩn khoa học:\n- Không cần pha nạp (loading phase) phức tạp: Chỉ cần duy trì 3-5g Creatine Monohydrate mỗi ngày, uống đều đặn sau buổi tập hoặc cùng bữa ăn có chứa carbohydrate.",
                'luot_xem' => 2840,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'DOMS (Đau mỏi cơ sau tập): Nguyên nhân và cách hồi phục nhanh',
                'chu_de' => 'Phục hồi & Y học thể thao',
                'anh_bia' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Cơn đau nhức cơ bắp xuất hiện sau 24-48 giờ tập luyện là gì và cách giảm đau mỏi hiệu quả.',
                'noi_dung' => "DOMS (Delayed Onset Muscle Soreness) là cảm giác đau nhức cơ bắp xuất hiện từ 24 đến 72 giờ sau khi hoàn thành một buổi tập nặng hoặc thực hiện bài tập mới lạ.\n\nNguyên nhân khoa học:\nNhiều người lầm tưởng DOMS là do tích tụ axit lactic, nhưng thực tế axit lactic biến mất chỉ sau 30-60 phút sau buổi tập. DOMS thực chất là kết quả của các vết rách siêu nhỏ (micro-tears) trên sợi cơ và phản ứng viêm tự nhiên đi kèm để sửa chữa và tái cấu trúc sợi cơ dày hơn.\n\nĐặc biệt, pha chuyển động hạ tạ (Eccentric phase) là nguyên nhân gây DOMS mạnh mẽ nhất.\n\nCách phục hồi nhanh chóng:\n- Phục hồi chủ động (Active recovery): Đi bộ nhẹ, bơi lội, giãn cơ động.\n- Uống đủ nước và bổ sung điện giải.\n- Ăn đủ đạm (1.6 - 2.2g/kg cân nặng) và ngủ đủ giấc.\n- Tắm nước ấm hoặc massage trị liệu nhẹ nhàng bằng con lăn (Foam Roller).",
                'luot_xem' => 1970,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nguyên lý Progressive Overload: Chìa khóa bắt buộc để phát triển cơ bắp',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Nếu không áp dụng Progressive Overload, cơ bắp sẽ ngừng phát triển dù bạn có tập chăm chỉ đến đâu.',
                'noi_dung' => "Progressive Overload (Tăng tiến áp lực) là nguyên lý cơ bản nhất trong thể hình: Cơ thể con người chỉ thích nghi và phát triển cơ bắp khi liên tục phải chịu đựng một mức tải trọng lớn hơn mức nó đã quen thuộc.\n\nCác cách tăng tiến áp lực chuẩn khoa học:\n1. Tăng mức tạ (Weight): Nâng mức tạ nặng hơn với cùng số lần lặp và kỹ thuật chuẩn.\n2. Tăng số lần lặp (Reps): Nâng cùng mức tạ nhưng tăng từ 8 reps lên 10-12 reps.\n3. Tăng số hiệp (Sets): Thêm 1 hiệp tập trong buổi tập.\n4. Giảm thời gian nghỉ giữa hiệp (Rest time): Giữ nguyên mức tạ và số rep nhưng rút ngắn thời gian nghỉ từ 90s xuống 60s.\n5. Tăng phạm vi chuyển động (Full Range of Motion - ROM) và kiểm soát tốc độ chuyển động (Tempo).\n\nLưu ý: Luôn đảm bảo kỹ thuật chuẩn xác (Form) trước khi tăng áp lực để tránh chấn thương khớp và dây chằng.",
                'luot_xem' => 3120,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'BMR và TDEE: Cách tính chuẩn để tăng cơ giảm mỡ chuẩn xác',
                'chu_de' => 'Dinh dưỡng & Chuyển hóa',
                'anh_bia' => 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiểu rõ lượng calo tiêu hao hàng ngày giúp bạn thiết lập thực đơn ăn uống không bao giờ lo thất bại.',
                'noi_dung' => "Để kiểm soát vóc dáng, việc nắm rõ mức năng lượng tiêu thụ của cơ thể là yếu tố quyết định hàng đầu:\n\n1. BMR (Basal Metabolic Rate - Tỷ lệ trao đổi chất cơ bản):\nLà lượng calo tối thiểu cơ thể cần để duy trì các chức năng sống cơ bản nhất (thở, tuần hoàn máu, hoạt động não bộ, tái tạo tế bào) khi bạn nằm yên một chỗ cả ngày.\n\n2. TDEE (Total Daily Energy Expenditure - Tổng năng lượng tiêu thụ hàng ngày):\nTDEE = BMR + Năng lượng vận động sinh hoạt (NEAT) + Năng lượng tập luyện (EAT) + Năng lượng tiêu hóa thức ăn (TEF).\n\nQuy tắc năng lượng:\n- Giảm mỡ (Cut): Ăn mức Calo In = TDEE - (300 đến 500 kcal).\n- Tăng cơ nạc (Lean Bulk): Ăn mức Calo In = TDEE + (200 đến 300 kcal).\n- Duy trì vóc dáng: Calo In = TDEE.",
                'luot_xem' => 4200,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cardio LISS vs Cardio HIIT: Lựa chọn nào tối ưu cho mục tiêu đốt mỡ?',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1434608519344-49d77a699e1d?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'So sánh chi tiết ưu nhược điểm của Cardio cường độ thấp kéo dài và Cardio ngắt quãng cường độ cao.',
                'noi_dung' => "Hai trường phái Cardio phổ biến nhất trong thể hình và giảm cân:\n\n1. LISS (Low-Intensity Steady-State Cardio):\n- Hình thức: Đi bộ dốc, đạp xe chậm, đi bộ nhanh duy trì nhịp tim ở vùng Zone 2 (60-70% nhịp tim tối đa) trong 30-60 phút.\n- Ưu điểm: Đốt cháy chủ yếu chất béo làm nhiên liệu, cực kỳ ít gây áp lực lên hệ thần kinh trung ương (CNS), không ảnh hưởng tiêu cực đến hiệu suất tập tạ ngày hôm sau.\n- Nhược điểm: Tốn nhiều thời gian.\n\n2. HIIT (High-Intensity Interval Training):\n- Hình thức: Luân phiên giữa các đợt bùng nổ hết sức (Sprint 20s) và nghỉ ngắn (40s) trong 15-20 phút.\n- Ưu điểm: Đốt calo nhanh, tạo hiệu ứng đốt mỡ sau tập (EPOC - Afterburn effect).\n- Nhược điểm: Rất nặng lên hệ thần kinh và khớp, dễ gây dị hóa cơ bắp nếu lạm dụng.\n\nLời khuyên: Kết hợp 70% LISS và 30% HIIT để tối ưu hóa sức khỏe tim mạch mà vẫn bảo toàn tối đa khối lượng cơ bắp.",
                'luot_xem' => 1650,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cơ lõi (Core) là gì và tại sao gập bụng không đồng nghĩa với tập core?',
                'chu_de' => 'Giải phẫu & Kỹ thuật',
                'anh_bia' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiểu đúng về hệ thống cơ lõi trung tâm giúp bạn có cột sống khỏe mạnh và nâng tạ an toàn hơn.',
                'noi_dung' => "Nhiều người thường đánh đồng cơ lõi (Core) với cơ 6 múi (Rectus Abdominis), nhưng trên thực tế hệ cơ lõi phức tạp và quan trọng hơn thế rất nhiều.\n\nCấu trúc hệ cơ lõi bao gồm:\n- Cơ bụng thẳng (Rectus Abdominis)\n- Cơ bụng ngang (Transverse Abdominis - chiếc đai nẹp tự nhiên của cột sống)\n- Cơ xiên trong và ngoài (Internal & External Obliques)\n- Cơ dựng sống (Erector Spinae) và cơ nhiều nhánh (Multifidus)\n- Cơ hoành (Diaphragm) và các cơ sàn chậu (Pelvic floor).\n\nChức năng cốt lõi:\nChức năng chính của Core là CHỐNG LẠI chuyển động (Anti-movement) để bảo vệ cột sống, bao gồm: Chống ưỡn (Anti-extension), Chống nghiêng (Anti-lateral flexion) và Chống xoay (Anti-rotation).\n\nCác bài tập Core chuẩn mực:\n- Plank, Ab Wheel Rollout (Chống ưỡn)\n- Side Plank, Suitcase Carry (Chống nghiêng)\n- Pallof Press, Bird Dog (Chống xoay).",
                'luot_xem' => 2310,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Intermittent Fasting (Nhịn ăn gián đoạn 16/8): Cơ chế và hiệu quả thực tế',
                'chu_de' => 'Dinh dưỡng & Giảm mỡ',
                'anh_bia' => 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Khám phá phương pháp nhịn ăn gián đoạn 16/8 giúp kích hoạt cơ chế tự thực bào (Autophagy) và kiểm soát đường huyết.',
                'noi_dung' => "Nhịn ăn gián đoạn (Intermittent Fasting - IF) là mô hình ăn uống luân phiên giữa chu kỳ ăn và chu kỳ nhịn ăn có chủ đích.\n\nMô hình phổ biến nhất: 16/8 (Nhịn ăn 16 tiếng và nạp toàn bộ lượng thức ăn trong khung giờ 8 tiếng mỗi ngày).\n\nCơ chế sinh học:\n1. Hạ mức Insulin: Khi nhịn ăn kéo dài trên 12 tiếng, nồng độ insulin trong máu giảm sâu, kích hoạt cơ thể chuyển sang sử dụng mỡ dự trữ làm nguồn năng lượng chính.\n2. Tự thực bào (Autophagy): Tế bào dọn dẹp các mảnh vụn protein hỏng và tái tạo tế bào mới khỏe mạnh hơn.\n3. Đơn giản hóa việc tạo thâm hụt calo mà không cần phải đong đếm quá chi li từng bữa ăn nhỏ.\n\nLưu ý quan trọng:\nTrong thời gian nhịn ăn 16h, bạn chỉ được uống nước lọc, trà xanh không đường hoặc cà phê đen nguyên chất (không calo). Khi vào khung 8h ăn uống, vẫn phải đảm bảo ăn đủ lượng Protein và dinh dưỡng đa lượng cần thiết.",
                'luot_xem' => 3890,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tầm quan trọng của giấc ngủ đối với sự phục hồi và Hormone tăng trưởng (GH)',
                'chu_de' => 'Phục hồi & Sức khỏe',
                'anh_bia' => 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Cơ bắp không phát triển trong phòng gym, chúng phát triển khi bạn ngủ say và hồi phục.',
                'noi_dung' => "Phòng gym là nơi bạn phá vỡ các sợi cơ; dinh dưỡng cung cấp vật liệu xây dựng; nhưng chính giấc ngủ mới là thời điểm cơ thể thực sự sửa chữa và tổng hợp cơ bắp mới.\n\nĐiều gì xảy ra khi bạn ngủ sâu (Giai đoạn NREM):\n1. Tiết Hormone tăng trưởng (Human Growth Hormone - HGH): Hơn 70% lượng HGH tự nhiên hàng ngày được tuyến yên giải phóng trong các đợt ngủ sâu đầu tiên của ban đêm.\n2. Hạ hormone dị hóa Cortisol: Thiếu ngủ kéo dài làm nồng độ Cortisol tăng cao, dẫn đến dị hóa teo cơ và tích tụ mỡ nội tạng.\n3. Tái nạp năng lượng hệ thần kinh: Phục hồi dẫn truyền thần kinh để duy trì sự tập trung và sức mạnh bùng nổ cho buổi tập tiếp theo.\n\nLời khuyên:\nDuy trì ngủ 7-9 tiếng mỗi đêm trong không gian tối, mát mẻ và hạn chế nhìn màn hình ánh sáng xanh trước khi ngủ 45 phút.",
                'luot_xem' => 2050,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Kỹ thuật Valsalva Maneuver: Cách hít thở an toàn và bùng nổ sức mạnh',
                'chu_de' => 'Kỹ thuật tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Phương pháp nén khí ổ bụng giúp khóa chặt cột sống khi thực hiện các bài tập gánh nặng như Squat, Deadlift.',
                'noi_dung' => "Kỹ thuật Valsalva (Valsalva Maneuver) là kỹ thuật hít thở chuyên nghiệp được sử dụng trong Powerlifting và cử tạ đỉnh cao để tạo áp lực nội khoang bụng (Intra-Abdominal Pressure - IAP).\n\nCách thực hiện chuẩn xác:\n1. Trước khi hạ tạ, hít một hơi thật sâu bằng cơ hoành (bụng phình ra 360 độ chứ không nâng ngực).\n2. Đóng thanh quản lại (ngậm chặt cổ họng như đang rặn nén hơi).\n3. Gồng chặt toàn bộ cơ bụng nén luồng khí lại, tạo thành một trụ khí vững chắc bao quanh cột sống thắt lưng.\n4. Thực hiện động tác hạ tạ và đẩy tạ qua điểm khó nhất (Sticking point) rồi mới từ từ thở xì hơi ra ngoài.\n\nLợi ích: Tăng độ vững của thân người lên 20-30%, bảo vệ đĩa đệm cột sống khỏi lực cắt và lực nén cực đại.",
                'luot_xem' => 1740,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // --- BÀI VIẾT BỔ SUNG MỚI ---
            [
                'tieu_de' => 'Whey Protein: Phân biệt Concentrate, Isolate và Hydrolyzed',
                'chu_de' => 'Thực phẩm bổ sung',
                'anh_bia' => 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiểu rõ các dòng Whey Protein trên thị trường để lựa chọn sản phẩm phù hợp với cơ địa và túi tiền.',
                'noi_dung' => "Whey Protein là sản phẩm phụ được tách ra trong quá trình sản xuất phô mai từ sữa bò. Tùy theo công nghệ lọc mà chia thành 3 dòng chính:\n\n1. Whey Protein Concentrate (WPC):\n- Độ tinh khiết: 70 - 80% protein.\n- Đặc điểm: Giữ lại nhiều hợp chất sinh học có lợi trong sữa, giá thành kinh tế nhất. Chứa một lượng nhỏ đường lactose và chất béo.\n- Đối tượng: Người bình thường không dị ứng với đường sữa lactose.\n\n2. Whey Protein Isolate (WPI):\n- Độ tinh khiết: 90 - 95% protein.\n- Đặc điểm: Được lọc bỏ gần như hoàn toàn lactose, chất béo và carbohydrate. Hấp thu cực nhanh.\n- Đối tượng: Người trong giai đoạn siết cơ (cutting), người bị bất dung nạp lactose (uống sữa bị đau bụng).\n\n3. Whey Protein Hydrolyzed (WPH):\n- Độ tinh khiết: Chứa các chuỗi peptide siêu nhỏ đã được thủy phân trước.\n- Đặc điểm: Tốc độ hấp thu nhanh nhất, hạn chế tối đa nguy cơ đầy bụng, giá thành cao nhất.\n\nThời điểm vàng sử dụng: Buổi sáng sau khi thức dậy và ngay sau buổi tập 30 - 45 phút.",
                'luot_xem' => 3190,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'BCAA và EAA: Bản chất axit amin thiết yếu và khi nào cần bổ sung?',
                'chu_de' => 'Thực phẩm bổ sung',
                'anh_bia' => 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Sự khác biệt giữa 3 axit amin chuỗi nhánh (BCAA) và 9 axit amin thiết yếu (EAA) trong việc chống dị hóa cơ.',
                'noi_dung' => "Cơ thể con người cần 20 loại axit amin để xây dựng protein, trong đó có 9 loại axit amin thiết yếu (EAA) mà cơ thể không thể tự tổng hợp được.\n\n1. BCAA (Branched-Chain Amino Acids):\n- Bao gồm 3 axit amin: Leucine, Isoleucine, và Valine.\n- Leucine đóng vai trò như chiếc công tắc khởi động con đường tổng hợp protein cơ bắp (mTOR pathway).\n\n2. EAA (Essential Amino Acids):\n- Bao gồm đầy đủ cả 9 axit amin thiết yếu (có chứa cả 3 BCAA bên trong).\n- Để xây dựng một ngôi nhà, BCAA là người bấm chuông bắt đầu xây, còn EAA là toàn bộ số gạch đá xi măng cần thiết.\n\nKhi nào bạn thực sự cần dùng?\n- Khi bạn tập luyện lúc bụng đói (Fasted training) để chống dị hóa teo cơ.\n- Khi chế độ ăn hàng ngày không đủ lượng protein chất lượng cao.\n- Nếu bạn đã uống đủ Whey Protein và ăn đủ thịt cá trứng, việc bổ sung thêm BCAA đơn lẻ là không quá cần thiết.",
                'luot_xem' => 1870,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Hypertrophy (Phì đại cơ bắp): 3 cơ chế khoa học kích thích tăng cơ',
                'chu_de' => 'Khoa học cơ bắp & Sinh lý học',
                'anh_bia' => 'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Nghiên cứu của Tiến sĩ Brad Schoenfeld về 3 trụ cột kích hoạt sự phát triển kích thước sợi cơ.',
                'noi_dung' => "Theo nghiên cứu kinh điển của Tiến sĩ Brad Schoenfeld, có 3 cơ chế chính thúc đẩy quá trình phì đại cơ bắp (Hypertrophy):\n\n1. Mechanical Tension (Áp lực cơ học):\n- Đây là yếu tố quan trọng nhất. Xảy ra khi sợi cơ phải co duỗi chống lại một mức tải trọng lớn trong toàn bộ phạm vi chuyển động.\n- Đạt được qua: Nâng tạ nặng (60-85% 1RM) với kỹ thuật kiểm soát chuẩn xác.\n\n2. Muscle Damage (Tổn thương cơ bắp):\n- Các vết rách siêu nhỏ xảy ra trên màng cơ (sarcolemma) và các sợi actin/myosin, đặc biệt trong pha hạ tạ (eccentric).\n- Kích hoạt phản ứng viêm lành tính và tế bào vệ tinh (satellite cells) để tái tạo sợi cơ dày hơn.\n\n3. Metabolic Stress (Áp lực chuyển hóa - Hiệu ứng Pump cơ):\n- Sự tích tụ các chất chuyển hóa như lactate, ion H+, phosphate vô cơ trong tế bào cơ khi tập số rep cao (12-20 reps) với thời gian chịu áp lực (TUT) kéo dài.\n- Khiến tế bào cơ trương phồng lên, kích thích giải phóng các hormone đồng hóa nội sinh.",
                'luot_xem' => 2750,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Deload Week (Tuần xả tải): Bí quyết vượt qua ngưỡng chững (Plateau)',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1517963879433-6ad2b056d712?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Nghỉ ngơi có chiến lược giúp phục hồi hệ thần kinh và khớp xương mà không hề làm mất đi khối lượng cơ bắp.',
                'noi_dung' => "Sau 4-8 tuần tập luyện cường độ cao liên tục, cơ thể bạn sẽ tích tụ sự mệt mỏi hệ thống (Systemic Fatigue), dẫn đến đau khớp, mất ngủ, giảm sức mạnh và chững cơ.\n\nDeload là một tuần giảm tải có chủ đích để cơ thể hồi phục hoàn toàn:\n\nCác phương pháp Deload phổ biến:\n1. Giảm mức tạ (Load Deload): Giữ nguyên số set và rep, nhưng giảm mức tạ xuống còn 50-60% so với tuần trước.\n2. Giảm khối lượng (Volume Deload): Giữ nguyên mức tạ nặng nhưng giảm 50% số hiệp tập (Ví dụ: từ 4 sets giảm còn 2 sets).\n3. Giảm cường độ (Intensity Deload): Tập cách ngưỡng thất bại từ 4-5 reps (RIR 4-5).\n\nLợi ích đạt được sau tuần Deload:\n- Hệ thần kinh trung ương (CNS) được làm mới hoàn toàn.\n- Giảm viêm gân và khớp.\n- Phá vỡ ngưỡng chững mức tạ ngay trong tuần tập tiếp theo.",
                'luot_xem' => 2130,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'RPE và RIR: Quản lý cường độ tập luyện chuẩn khoa học',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Thang đo cảm nhận nỗ lực (RPE) và số rep dự trữ (RIR) giúp bạn tự điều chỉnh tải trọng theo thể trạng hàng ngày.',
                'noi_dung' => "Thay vì áp dụng mức tạ cố định theo tỷ lệ % 1RM, các vận động viên hiện đại sử dụng thang đo RPE và RIR để tự động điều chỉnh theo năng lượng thực tế trong ngày.\n\n1. RIR (Reps In Reserve - Số rep còn có thể làm được trước khi thất bại hoàn toàn):\n- RIR 0: Thất bại hoàn toàn (Failure), không thể làm thêm dù chỉ 1 rep.\n- RIR 1: Dừng lại khi cảm thấy chỉ còn ráng được đúng 1 rep nữa.\n- RIR 2: Dừng lại khi còn có thể làm thêm 2 reps nữa.\n- RIR 3: Dừng lại khi còn có thể làm thêm 3 reps nữa.\n\n2. Thang đo RPE (Rate of Perceived Exertion):\n- RPE 10 = RIR 0 (Hết sức tối đa)\n- RPE 9 = RIR 1 (Rất nặng, còn 1 rep)\n- RPE 8 = RIR 2 (Nặng vừa phải, còn 2 reps)\n- RPE 7 = RIR 3 (Mức tạ khởi động hoặc tập kỹ thuật)\n\nLời khuyên vàng: Vùng hiệu quả nhất để tăng cơ mà không làm kiệt quệ hệ thần kinh là duy trì ở mức RPE 7.5 đến RPE 9 (tương đương RIR 1-2).",
                'luot_xem' => 1980,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Pre-Workout & Caffeine: Tác động sinh lý và cách dùng không bị lờn thuốc',
                'chu_de' => 'Thực phẩm bổ sung',
                'anh_bia' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Cơ chế tác động của Pre-workout đến sự tập trung, giãn mạch và cách chu kỳ hóa sử dụng thông minh.',
                'noi_dung' => "Pre-workout là sản phẩm bổ sung tăng cường năng lượng và độ tập trung trước buổi tập.\n\nThành phần chủ chốt và cơ chế:\n1. Caffeine Anhydrous: Ức chế thụ thể Adenosine trong não bộ, ngăn chặn tín hiệu gây mệt mỏi và tăng cường giải phóng Dopamine, Adrenaline.\n2. L-Citrulline / Citrulline Malate: Thúc đẩy sản sinh Nitric Oxide (NO), làm giãn nở mạch máu giúp tăng lưu lượng máu và oxy tới cơ bắp (hiệu ứng Pump cực đại).\n3. Beta-Alanine: Tăng tổng hợp Carnosine trong cơ, giúp đệm giảm nồng độ axit lactic gây mỏi cơ (tạo cảm giác châm chích ngứa ngáy ngoài da).\n\nCách chống lờn Caffeine (Tolerance reset):\n- Sử dụng 200 - 300mg Caffeine trước tập 30 - 45 phút.\n- Không dùng sau 17h chiều để tránh phá hủy chất lượng giấc ngủ.\n- Sau 4-6 tuần sử dụng liên tục, nên nghỉ hoàn toàn caffeine trong 1-2 tuần để thiết lập lại độ nhạy của thụ thể não bộ.",
                'luot_xem' => 2640,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Mind-Muscle Connection: Bí quyết kết nối Thần kinh - Cơ bắp',
                'chu_de' => 'Kỹ thuật tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1534367507873-d2d7e24c797f?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Tập trung suy nghĩ vào cơ bắp mục tiêu có thực sự giúp tăng kích hoạt sợi cơ nhiều hơn?',
                'noi_dung' => "Mind-Muscle Connection (Kết nối thần kinh - cơ bắp) là khả năng tập trung tâm trí và chủ động điều khiển sự co bóp của một nhóm cơ nhất định trong suốt động tác.\n\nBằng chứng điện cơ đồ (EMG):\nCác nghiên cứu khoa học sử dụng thiết bị đo điện cơ (EMG) cho thấy khi người tập chủ động 'nghĩ về cơ bắp mục tiêu' (Internal focus), tín hiệu kích hoạt các đơn vị vận động (Motor units) trong nhóm cơ đó tăng thêm từ 15 - 25%.\n\nCách cải thiện kết nối thần kinh - cơ bắp:\n1. Hạ bớt mức tạ xuống để kiểm soát hoàn toàn chuyển động.\n2. Áp dụng kỹ thuật co bóp đỉnh điểm (Peak Contraction): Giữ chặt và siết cứng cơ mục tiêu trong 1-2 giây ở điểm co ngắn nhất.\n3. Làm chậm pha hạ tạ (Eccentric tempo 3-4 giây).\n4. Chạm tay vào nhóm cơ mục tiêu (hoặc nhờ bạn tập chạm nhẹ) trước khi thực hiện set tập để tăng kích thích xúc giác.",
                'luot_xem' => 2280,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Đau gối khi Squat và hiện tượng sụp gối (Knee Valgus): Cách xử lý triệt để',
                'chu_de' => 'Phục hồi & Phòng ngừa chấn thương',
                'anh_bia' => 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Nguyên nhân gây đau gối khi gánh tạ và các bài tập củng cố cơ mông nhỡ, cổ chân để bảo vệ khớp gối.',
                'noi_dung' => "Đau khớp gối khi Squat là một trong những phàn nàn phổ biến nhất ở gymer. Hiện tượng nguy hiểm nhất là Knee Valgus (đầu gối bị sụp vào trong khi đứng lên).\n\nNguyên nhân chính:\n1. Cơ mông nhỡ (Gluteus Medius) bị yếu: Không đủ lực để giữ xương đùi xoay ngoài ổn định.\n2. Cổ chân bị cứng (Thiếu Dorsiflexion): Khớp cổ chân không gập đủ độ khiến cơ thể tự bù trừ bằng cách bẻ gập đầu gối vào trong.\n3. Đặt góc bàn chân và đầu gối không đồng trục.\n\nCách khắc phục hiệu quả:\n- Sử dụng dây kháng lực (Mini band) quấn quanh đùi khi khởi động (bài Crab Walk, Glute Bridge) để kích hoạt cơ mông nhỡ.\n- Giãn bắp chân và cải thiện độ linh hoạt cổ chân bằng các bài ép dẻo cổ chân với dây thun.\n- Luôn chú ý mở đầu gối hướng theo chiều mũi chân trong suốt quá trình đi xuống và đứng lên.",
                'luot_xem' => 1910,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Hội chứng Chèn ép khớp vai (Shoulder Impingement) khi đẩy ngực',
                'chu_de' => 'Phục hồi & Phòng ngừa chấn thương',
                'anh_bia' => 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Bảo vệ nhóm chóp xoay (Rotator Cuff) và kỹ thuật rút xương bả vai (Scapular Retraction) khi Bench Press.',
                'noi_dung' => "Shoulder Impingement xảy ra khi gân cơ trên gai (Supraspinatus tendon) trong nhóm chóp xoay bị chèn ép cọ xát vào mỏm cùng vai (Acromion), gây viêm đau nhức buốt khi giơ tay hoặc đẩy ngực.\n\nSai lầm phổ biến khi Bench Press:\n- Để cùi chỏ mở rộng vuông góc 90 độ so với thân người (Flaring elbows).\n- Thả lỏng bả vai, vai bị nhô về phía trước khi hạ tạ xuống ngực.\n\nKỹ thuật an toàn cho khớp vai:\n1. Thu và ghìm chặt bả vai xuống dưới và ra sau (Retract & Depress Scapula) tạo thành điểm tựa vững chắc trên ghế phẳng.\n2. Khép cùi chỏ tạo thành góc khoảng 45 - 60 độ so với thân người (Arrow shape).\n3. Hạ thanh tạ chạm vào vùng ngực dưới/mũi ức thay vì chạm lên ngực trên sát cổ.\n4. Khởi động nhóm cơ xoay vai với dây thun (Face Pulls, Band External Rotations) trước mỗi buổi tập thân trên.",
                'luot_xem' => 2480,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tập luyện đến ngưỡng thất bại (Training to Failure): Lợi ích và rủi ro',
                'chu_de' => 'Phương pháp tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Khi nào nên tập tới ngưỡng thất bại hoàn toàn và khi nào nên dừng lại trước ngưỡng để tối ưu hóa sự phục hồi.',
                'noi_dung' => "Tập đến ngưỡng thất bại (Muscular Failure) là trạng thái bạn không thể hoàn thành thêm bất kỳ một lần lặp nào nữa với kỹ thuật chuẩn mực.\n\nLợi ích:\n- Huy động tối đa 100% các đơn vị vận động sợi cơ loại II (sợi cơ phản ứng nhanh có tiềm năng phì đại lớn nhất).\n- Rất hiệu quả khi áp dụng cho các bài tập khu cơ (Isolation) như bắp tay, vai bên, bắp chân.\n\nRủi ro nếu lạm dụng:\n- Gây kiệt quệ hệ thần kinh trung ương (CNS Fatigue), mất nhiều ngày để hồi phục.\n- Làm sụt giảm hiệu suất và số rep của các hiệp tập tiếp theo trong buổi tập.\n- Nguy cơ chấn thương cực cao nếu áp dụng failure trên các bài Compound nặng như Squat, Deadlift, Overhead Press.\n\nChiến lược tối ưu:\nChỉ nên tập đến failure ở hiệp cuối cùng (Last set) của các bài tập máy hoặc bài isolation.",
                'luot_xem' => 1630,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Giảm mỡ cục bộ (Spot Reduction): Huyền thoại và Sự thật khoa học',
                'chu_de' => 'Khoa học & Thần thoại',
                'anh_bia' => 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Tại sao gập bụng nghìn cái không làm tan mỡ bụng và cơ chế huy động axit béo thực sự diễn ra như thế nào.',
                'noi_dung' => "Nhiều người tin rằng muốn giảm mỡ bụng thì phải gập bụng thật nhiều, muốn giảm mỡ đùi thì phải tập đá đùi liên tục. Đây là huyền thoại lớn nhất trong ngành thể hình mang tên 'Spot Reduction'.\n\nCơ chế giải phóng mỡ khoa học:\nKhi cơ thể cần năng lượng dự trữ, hormone (như Adrenaline, Noradrenaline) được tiết vào máu và gắn vào các thụ thể Adrenergic trên tế bào mỡ khắp toàn bộ cơ thể. Enzyme lipase sẽ phân giải triglyceride thành axit béo tự do đi vào dòng máu để đến các cơ quan cần năng lượng.\n\nCơ thể bạn tự quyết định đốt mỡ ở đâu trước dựa trên yếu tố di truyền, giới tính và mật độ thụ thể Alpha/Beta trên tế bào mỡ của từng vùng, chứ không phụ thuộc vào nhóm cơ bạn vừa co bóp.\n\nGiải pháp duy nhất: Duy trì thâm hụt calo bền vững và tập kháng lực toàn thân, mỡ toàn cơ thể sẽ giảm dần đều và cuối cùng sẽ tới vùng mỡ cứng đầu (bụng dưới, eo lưng).",
                'luot_xem' => 3780,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Nước và Điện giải (Natri, Kali, Magie): Tác động đến sự co cơ và chuột rút',
                'chu_de' => 'Dinh dưỡng & Sinh lý học',
                'anh_bia' => 'https://images.unsplash.com/photo-1559839914-ba2a201c1f51?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Mất nước chỉ 2% có thể làm giảm 15% sức mạnh nâng tạ. Vai trò sống còn của khoáng chất điện giải.',
                'noi_dung' => "Cơ bắp chứa tới hơn 75% là nước. Nước và các ion khoáng chất đóng vai trò thiết yếu trong việc dẫn truyền xung động thần kinh và điều khiển chu kỳ co giãn của sợi cơ.\n\nVai trò của các chất điện giải chính:\n1. Natri (Sodium): Duy trì áp suất thẩm thấu ngoại bào và kích hoạt điện thế hoạt động (Action potential) để cơ bắp nhận lệnh co từ não bộ. Đừng quá kiêng muối khi tập nặng!\n2. Kali (Potassium): Cân bằng ion nội bào, giúp cơ bắp thư giãn sau khi co bóp.\n3. Magie (Magnesium): Hỗ trợ hơn 300 phản ứng enzyme, tổng hợp protein và ngăn ngừa hiện tượng co thắt cơ bắp cục bộ (chuột rút).\n4. Canxi (Calcium): Giải phóng từ mạng nội chất để actin gắn vào myosin thực hiện động tác gập cơ.\n\nKhuyến nghị: Uống 500ml nước trước tập 2 tiếng, nhấp từng ngụm nhỏ trong buổi tập và bổ sung thêm 1 nhúm muối hồng hoặc bột điện giải trong những ngày tập nặng ra nhiều mồ hôi.",
                'luot_xem' => 1490,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Carb Cycling (Xoay vòng tinh bột): Chiến lược giảm mỡ giữ cơ đỉnh cao',
                'chu_de' => 'Dinh dưỡng nâng cao',
                'anh_bia' => 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Cách luân phiên giữa các ngày High Carb, Low Carb và No Carb để tối ưu hóa Insulin và đốt mỡ hiệu quả.',
                'noi_dung' => "Carb Cycling là phương pháp điều chỉnh lượng carbohydrate nạp vào theo từng ngày trong tuần tùy thuộc vào cường độ vận động của ngày hôm đó.\n\nCấu trúc một tuần Carb Cycling mẫu:\n1. Ngày High Carb (Carb cao): Áp dụng vào những ngày tập nặng nhất (Chân hoặc Lưng xô).\n- Tác dụng: Nạp đầy kho dự trữ Glycogen, đẩy mạnh chuyển hóa, tăng hormone Leptin giúp chống lại trạng thái sinh tồn kiệt quệ khi ăn kiêng.\n2. Ngày Moderate Carb (Carb vừa): Áp dụng vào những ngày tập nhóm cơ nhỏ hơn (Ngực, Vai, Tay).\n- Tác dụng: Cung cấp vừa đủ năng lượng để duy trì hiệu suất tập luyện.\n3. Ngày Low Carb / No Carb (Carb thấp): Áp dụng vào ngày nghỉ hoặc ngày chỉ tập Cardio nhẹ.\n- Tác dụng: Đẩy mức Insulin xuống thấp tối đa, bắt cơ thể sử dụng mỡ thừa làm nguồn năng lượng chính.",
                'luot_xem' => 2890,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Deadlift: Phân biệt Conventional, Sumo và Romanian Deadlift (RDL)',
                'chu_de' => 'Kỹ thuật tập luyện',
                'anh_bia' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Mỗi biến thể Deadlift tác động vào nhóm cơ nào và đâu là lựa chọn phù hợp nhất với cấu trúc giải phẫu của bạn.',
                'noi_dung' => "Deadlift là vua của các bài tập xây dựng chuỗi cơ sau (Posterior Chain). Dưới đây là 3 biến thể phổ biến nhất:\n\n1. Conventional Deadlift (Deadlift truyền thống):\n- Tư thế: Hai chân rộng bằng hông, hai tay nắm thanh tạ bên ngoài chân.\n- Tác động: Cơ lưng dưới (Erector spinae), cơ mông, đùi sau và toàn bộ cơ lưng xô.\n- Phù hợp: Người có thân trên ngắn, tay dài.\n\n2. Sumo Deadlift:\n- Tư thế: Hai chân đứng rộng gấp đôi vai, mũi chân xoay ngoài 45 độ, hai tay nắm bên trong hai chân.\n- Tác động: Tập trung áp lực cực lớn lên cơ mông (Glutes), đùi trong (Adductors) và đùi trước, giảm tải đáng kể lực cắt lên cột sống thắt lưng.\n- Phù hợp: Người có thân trên dài, tay ngắn hoặc có vấn đề về thắt lưng.\n\n3. Romanian Deadlift (RDL):\n- Tư thế: Khởi đầu từ tư thế đứng thẳng, gập hông đẩy mông ra sau (Hinge) với khớp gối chỉ hơi cong nhẹ.\n- Tác động: Căng giãn tối đa cơ đùi sau (Hamstrings) và cơ mông theo chiều dọc.",
                'luot_xem' => 3340,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Hormone Testosterone tự nhiên: 7 cách tăng cường không cần dùng thuốc',
                'chu_de' => 'Dược lý & Sinh lý nam',
                'anh_bia' => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Testosterone là hormone quyết định sức mạnh, mật độ cơ bắp và sự nam tính. Cách kích hoạt testosterone tự nhiên.',
                'noi_dung' => "Testosterone đóng vai trò then chốt trong quá trình tổng hợp protein, duy trì mật độ xương và sức khỏe tinh thần ở nam giới.\n\n7 biện pháp khoa học giúp tối ưu hóa Testosterone tự nhiên:\n1. Nâng tạ nặng với các bài Compound (Squat, Deadlift, Bench Press, Pull-up).\n2. Không ăn kiêng chất béo quá mức: Tối thiểu 20-30% calo hàng ngày nên đến từ chất béo lành mạnh (trứng gà, dầu ô liu, quả bơ, mỡ cá) vì cholesterol là tiền chất tổng hợp testosterone.\n3. Duy trì tỷ lệ mỡ cơ thể lý tưởng (10 - 15% đối với nam giới). Quá béo sẽ làm tăng enzyme Aromatase biến đổi Testosterone thành Estrogen.\n4. Bổ sung Kẽm (Zinc) và Vitamin D3 (hoặc tắm nắng 15-20 phút mỗi sáng).\n5. Ngủ đủ 7 - 8 tiếng mỗi đêm.\n6. Kiểm soát căng thẳng để ngăn chặn hormone Cortisol ức chế sản sinh testosterone.\n7. Hạn chế uống nhiều rượu bia và nước ngọt có ga.",
                'luot_xem' => 4560,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Giãn cơ tĩnh (Static) và Giãn cơ động (Dynamic): Sử dụng đúng lúc',
                'chu_de' => 'Phục hồi & Khởi động',
                'anh_bia' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Sai lầm giãn cơ tĩnh trước buổi tập làm giảm sức mạnh và cách thiết lập quy trình khởi động chuẩn mực.',
                'noi_dung' => "Giãn cơ là phần không thể thiếu trong bất kỳ giáo án tập luyện nào, nhưng áp dụng sai thời điểm có thể phản tác dụng:\n\n1. Giãn cơ động (Dynamic Stretching - Dùng TRƯỚC tập):\n- Hình thức: Các chuyển động liên tục đưa khớp qua toàn bộ biên độ (Vung chân, xoay tay, sâu đo, lunge bước dài).\n- Lợi ích: Tăng nhiệt độ cơ bắp, bôi trơn chất lỏng hoạt dịch trong khớp, đánh thức hệ thần kinh mà không làm giảm lực co bóp của cơ.\n\n2. Giãn cơ tĩnh (Static Stretching - Dùng SAU tập):\n- Hình thức: Kéo giãn cơ bắp đến điểm căng tối đa và giữ yên trong 20-45 giây.\n- Tác hại nếu làm trước tập: Làm giãn thụ thể thoi cơ (Muscle spindles), khiến lực phát động tối đa (Peak power) bị suy giảm từ 5-10%.\n- Lợi ích khi làm sau tập: Giúp hạ nhịp tim, chuyển hệ thần kinh từ trạng thái giao cảm (căng thẳng) sang phó giao cảm (phục hồi), kéo dài chiều dài cơ bắp.",
                'luot_xem' => 1760,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Cửa sổ đồng hóa (Anabolic Window): Có bắt buộc phải nạp Protein ngay lập tức?',
                'chu_de' => 'Dinh dưỡng & Huyền thoại',
                'anh_bia' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Khoa học hiện đại đã chứng minh khái niệm cửa sổ 30 phút sau tập không hề khắt khe như chúng ta từng nghĩ.',
                'noi_dung' => "Trong nhiều thập kỷ, văn hóa phòng gym cho rằng bạn phải uống ngay bình lắc Whey Protein trong vòng 30 phút sau khi đặt tạ xuống, nếu không buổi tập sẽ trở nên vô nghĩa.\n\nSự thật từ các nghiên cứu Meta-Analysis của Schoenfeld & Aragon:\n1. Quá trình tổng hợp protein cơ bắp (Muscle Protein Synthesis - MPS) sau buổi tập kháng lực thực chất kéo dài và duy trì ở mức cao từ 24 đến 48 giờ.\n2. Yếu tố quan trọng nhất quyết định sự phát triển cơ bắp là TỔNG LƯỢNG PROTEIN nạp vào trong cả ngày (1.6 - 2.2g/kg thể trọng) chứ không phải thời điểm chính xác từng phút.\n3. Nếu bạn đã có một bữa ăn đủ đạm trước khi tập từ 1-2 tiếng, lượng axit amin trong máu vẫn còn dồi dào suốt buổi tập và kéo dài thêm nhiều giờ sau đó.\n\nKhuyến nghị: Bạn chỉ cần ăn bữa ăn giàu protein chất lượng cao trong vòng 1-2 giờ sau buổi tập là đã đạt được hiệu quả đồng hóa tối đa.",
                'luot_xem' => 2530,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'tieu_de' => 'Tập luyện và Chu kỳ kinh nguyệt: Cách điều chỉnh giáo án theo từng pha Hormone',
                'chu_de' => 'Thể hình nữ & Sinh lý học',
                'anh_bia' => 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=800&q=80',
                'tom_tat' => 'Hiểu rõ sự biến thiên của Estrogen và Progesterone giúp nữ gymer tập luyện hiệu quả và tránh kiệt sức.',
                'noi_dung' => "Sự thay đổi nồng độ hormone sinh dục nữ trong chu kỳ 28 ngày ảnh hưởng trực tiếp đến sức mạnh, khả năng phục hồi và mức độ giữ nước của cơ thể:\n\n1. Pha nang noãn (Follicular Phase - Từ ngày 1 đến ngày 14):\n- Đặc điểm: Nồng độ Estrogen tăng cao. Estrogen là hormone hỗ trợ đồng hóa, tăng khả năng chịu đau và phục hồi cơ bắp rất tốt.\n- Chiến lược tập: Đây là thời điểm phụ nữ có sức mạnh tốt nhất trong tháng. Hãy đẩy mạnh tạ nặng, tập Progressive Overload và các bài tập cường độ cao (HIIT).\n\n2. Pha rụng trứng (Ovulation - Khoảng ngày 14):\n- Sức mạnh đạt đỉnh, tuy nhiên nồng độ Estrogen cao nhất cũng làm dây chằng khớp gối lỏng lẻo hơn, cần cẩn thận khi tập các bài nhảy bật hoặc chuyển hướng đột ngột.\n\n3. Pha hoàng thể (Luteal Phase - Từ ngày 15 đến ngày 28):\n- Đặc điểm: Nồng độ Progesterone tăng vọt. Nhiệt độ cơ thể tăng, dễ mệt mỏi, khả năng sử dụng carb kém hơn và cơ thể tích nước.\n- Chiến lược tập: Giảm cường độ tập, tập các bài tạ vừa phải, ưu tiên cardio nhẹ (LISS), yoga và chú ý uống đủ nước.",
                'luot_xem' => 2010,
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
