<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChuongTrinhTapSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('chuong_trinh_tap')->truncate();

        DB::table('chuong_trinh_tap')->insert([
            // Mục tiêu Nam
            [
                'id_chuong_trinh' => 1,
                'ten_chuong_trinh' => 'Tăng cơ bắp',
                'mo_ta' => 'Phát triển khối lượng cơ toàn thân với lộ trình tăng tải khoa học.',
                'muc_tieu' => 'Tăng cơ bắp',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 2,
                'ten_chuong_trinh' => 'Tay to khỏe',
                'mo_ta' => 'Tập trung phát triển cơ tay trước, tay sau và lực cầm nắm.',
                'muc_tieu' => 'Phát triển cơ tay',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://yamaguchi.com.vn/media/news/2311_co-cang-tay-mot-trong-nhung-nhom-co-cung-dau-kho-tap-nhat-cua-canh-tay.jpg',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 3,
                'ten_chuong_trinh' => 'Ngực vạm vỡ',
                'mo_ta' => 'Xây dựng cơ ngực dày, cân đối và cải thiện sức mạnh thân trên.',
                'muc_tieu' => 'Phát triển cơ ngực',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 4,
                'ten_chuong_trinh' => 'Lưng rộng',
                'mo_ta' => 'Phát triển cơ xô và lưng giữa để tạo vóc dáng chữ V khỏe khoắn.',
                'muc_tieu' => 'Phát triển cơ lưng',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1507398941214-572c25f4b1dc?q=80&w=1373&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 5,
                'ten_chuong_trinh' => 'Vai rộng',
                'mo_ta' => 'Phát triển toàn diện vai trước, vai giữa và vai sau.',
                'muc_tieu' => 'Phát triển cơ vai',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUwnzt21TsbRz7k9Fg1fmJpHz8ixyUpXlvaaFdg8q2H5BoIPPjbqkMUIhg&s=10',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 6,
                'ten_chuong_trinh' => 'Chân chắc khỏe',
                'mo_ta' => 'Tăng sức mạnh đùi, mông, bắp chân và cải thiện khả năng vận động.',
                'muc_tieu' => 'Phát triển thân dưới',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1683509231125-5c487afaa453?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8Zml0bmVzcyUyMG1lbnxlbnwwfHwwfHx8MA%3D%3D',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 7,
                'ten_chuong_trinh' => 'Giảm cân',
                'mo_ta' => 'Kết hợp cardio và kháng lực để tăng tiêu hao năng lượng bền vững.',
                'muc_tieu' => 'Giảm cân',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1486218119243-13883505764c?q=80&w=1472&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 8,
                'ten_chuong_trinh' => 'Cơ thể sắc nét',
                'mo_ta' => 'Giảm mỡ và duy trì cơ bắp để vóc dáng săn chắc, rõ nét hơn.',
                'muc_tieu' => 'Siết cơ giảm mỡ',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 9,
                'ten_chuong_trinh' => 'Cơ bụng 6 múi',
                'mo_ta' => 'Tăng sức mạnh vùng core kết hợp vận động hỗ trợ giảm mỡ toàn thân.',
                'muc_tieu' => 'Phát triển cơ bụng',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://png.pngtree.com/thumb_back/fw800/background/20250913/pngtree-ripped-male-sixpack-torso-image_19298269.webp',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 10,
                'ten_chuong_trinh' => 'Powerlifting',
                'mo_ta' => 'Phát triển sức mạnh với ba động tác squat, bench press và deadlift.',
                'muc_tieu' => 'Tăng sức mạnh',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 56,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 11,
                'ten_chuong_trinh' => 'CrossFit',
                'mo_ta' => 'Kết hợp sức mạnh, sức bền và vận động chức năng ở cường độ cao.',
                'muc_tieu' => 'Tăng thể lực',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Phòng CrossFit',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1601422407692-ec4eeec1d9b3?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y3Jvc3NmaXR8ZW58MHx8MHx8fDA%3D',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 12,
                'ten_chuong_trinh' => 'Tập toàn thân 45 phút',
                'mo_ta' => 'Buổi tập toàn thân cân bằng, phù hợp người có ít thời gian.',
                'muc_tieu' => 'Tập toàn thân',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 0,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1669322779651-5ca89652492e?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Z3ltJTIwcGVvcGxlfGVufDB8fDB8fHww',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Mục tiêu Nữ
            [
                'id_chuong_trinh' => 13,
                'ten_chuong_trinh' => 'Giảm cân',
                'mo_ta' => 'Kết hợp cardio và kháng lực giúp kiểm soát cân nặng an toàn.',
                'muc_tieu' => 'Giảm cân',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 14,
                'ten_chuong_trinh' => 'Cơ thể sắc nét',
                'mo_ta' => 'Cải thiện độ săn chắc và đường nét cơ thể bằng bài tập toàn diện.',
                'muc_tieu' => 'Siết cơ giảm mỡ',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?q=80&w=1469&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 15,
                'ten_chuong_trinh' => 'Vòng ba hoàn hảo',
                'mo_ta' => 'Tập trung phát triển cơ mông và cải thiện sức mạnh thân dưới.',
                'muc_tieu' => 'Phát triển cơ mông',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://sunfitness.vn/wp-content/uploads/2023/08/tap-gym-tang-vong-3-1.jpg.webp',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 16,
                'ten_chuong_trinh' => 'Cơ bụng 6 múi',
                'mo_ta' => 'Củng cố vùng core và hỗ trợ xây dựng vòng eo săn chắc.',
                'muc_tieu' => 'Phát triển cơ bụng',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 17,
                'ten_chuong_trinh' => 'Tăng cơ bắp',
                'mo_ta' => 'Phát triển cơ bắp cân đối, tăng sức mạnh và cải thiện vóc dáng.',
                'muc_tieu' => 'Tăng cơ bắp',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1534258936925-c58bed479fcb?q=80&w=1631&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 18,
                'ten_chuong_trinh' => 'Powerlifting',
                'mo_ta' => 'Rèn luyện sức mạnh với squat, bench press và deadlift đúng kỹ thuật.',
                'muc_tieu' => 'Tăng sức mạnh',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 56,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 19,
                'ten_chuong_trinh' => 'CrossFit',
                'mo_ta' => 'Nâng cao sức mạnh, sức bền và khả năng vận động toàn thân.',
                'muc_tieu' => 'Tăng thể lực',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Phòng CrossFit',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 20,
                'ten_chuong_trinh' => 'Tập toàn thân 45 phút',
                'mo_ta' => 'Chương trình toàn thân ngắn gọn giúp duy trì sức khỏe và vóc dáng.',
                'muc_tieu' => 'Tập toàn thân',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 21,
                'ten_chuong_trinh' => 'Phục hồi sau sinh',
                'mo_ta' => 'Vận động nhẹ giúp phục hồi core và thể lực sau sinh theo lộ trình.',
                'muc_tieu' => 'Phục hồi sau sinh',
                'nhom_muc_tieu' => 1,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 1,
                'noi_tap' => 'Tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 3,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1520&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Chương trình chung khi tắt mục tiêu
            [
                'id_chuong_trinh' => 22,
                'ten_chuong_trinh' => 'Khởi động toàn thân',
                'mo_ta' => 'Đánh thức các nhóm cơ và chuẩn bị khớp trước buổi tập chính.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Mọi nơi',
                'so_ngay' => 14,
                'so_buoi_moi_tuan' => 3,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?q=80&w=1520&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 23,
                'ten_chuong_trinh' => 'Toàn thân cho người mới',
                'mo_ta' => 'Làm quen các chuyển động nền tảng với cường độ vừa phải.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 30,
                'so_buoi_moi_tuan' => 3,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 24,
                'ten_chuong_trinh' => 'Cardio đốt năng lượng',
                'mo_ta' => 'Tăng nhịp tim và cải thiện sức bền bằng chuỗi cardio liên tục.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Gym hoặc ngoài trời',
                'so_ngay' => 28,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://plus.unsplash.com/premium_photo-1679938885972-180ed418f466?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8Y2FyZGlvfGVufDB8fDB8fHww',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 25,
                'ten_chuong_trinh' => 'Thân trên toàn diện',
                'mo_ta' => 'Phối hợp các bài tập ngực, lưng, vai và tay trong một buổi.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 35,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 26,
                'ten_chuong_trinh' => 'Thân dưới toàn diện',
                'mo_ta' => 'Phát triển đồng đều cơ mông, đùi trước, đùi sau và bắp chân.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 35,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1434596922112-19c563067271?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 27,
                'ten_chuong_trinh' => 'Core vững chắc',
                'mo_ta' => 'Củng cố bụng, lưng dưới và khả năng giữ ổn định cơ thể.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Trung cấp',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 28,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 28,
                'ten_chuong_trinh' => 'HIIT toàn thân',
                'mo_ta' => 'Chuỗi vận động cường độ cao giúp nâng cao sức bền và thể lực.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Gym hoặc tại nhà',
                'so_ngay' => 28,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8aGlpdHxlbnwwfHwwfHx8MA%3D%3D',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 29,
                'ten_chuong_trinh' => 'Sức mạnh nền tảng',
                'mo_ta' => 'Rèn luyện các chuyển động compound và kỹ thuật tăng tải an toàn.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Nâng cao',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Phòng gym',
                'so_ngay' => 42,
                'so_buoi_moi_tuan' => 4,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 30,
                'ten_chuong_trinh' => 'Mobility và giãn cơ',
                'mo_ta' => 'Cải thiện biên độ vận động, độ linh hoạt và khả năng phục hồi.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Mọi nơi',
                'so_ngay' => 21,
                'so_buoi_moi_tuan' => 3,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1518611012118-696072aa579a?q=80&w=1470&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id_chuong_trinh' => 31,
                'ten_chuong_trinh' => 'Tập nhanh 20 phút',
                'mo_ta' => 'Buổi tập ngắn gọn, thuận tiện để duy trì thói quen mỗi ngày.',
                'muc_tieu' => null,
                'nhom_muc_tieu' => 0,
                'cap_do' => 'Cơ bản',
                'gioi_tinh_ap_dung' => 2,
                'noi_tap' => 'Mọi nơi',
                'so_ngay' => 21,
                'so_buoi_moi_tuan' => 5,
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1486218119243-13883505764c?q=80&w=1472&auto=format&fit=crop',
                'tinh_trang' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}



