<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MonAnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('mon_an')->truncate();

        DB::table('mon_an')->insert([
            // ==================== 1. DAIRY (Sữa và các sản phẩm từ sữa) ====================
            [
                'ten_mon_an' => 'Bánh bao lười phô mai tươi (Cottage Cheese)',
                'danh_muc_slug' => 'dairy',
                'danh_muc_ten' => 'Sữa và các sản phẩm từ sữa, sữa chua, phô mai cottage',
                'mo_ta' => 'Món bánh bao làm từ phô mai cottage giàu casein protein, giải phóng axit amin chậm nuôi dưỡng cơ bắp.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 200,
                'calo' => 177,
                'thoi_gian_nau' => 15,
                'protein' => 14.3,
                'carb' => 17.6,
                'fat' => 5.1,
                'nguyen_lieu' => "Phô mai tươi 5% (100g)\nBột gạo trắng (40g)\nTrứng gà (1 quả)\nChất tạo ngọt tự nhiên (Stevia)",
                'huong_dan_nau' => "1. Trộn đều phô mai cottage với trứng gà và đường ăn kiêng.\n2. Cho bột gạo vào nhào nhẹ, tạo hình bánh bao nhỏ.\n3. Luộc bánh trong nước sôi khoảng 3-5 phút đến khi nổi lên là chín.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Sữa chua Hy Lạp hạt chia & mật ong',
                'danh_muc_slug' => 'dairy',
                'danh_muc_ten' => 'Sữa và các sản phẩm từ sữa, sữa chua, phô mai cottage',
                'mo_ta' => 'Sữa chua Hy Lạp tách nước giàu đạm tự nhiên kết hợp hạt chia cung cấp omega-3 và chất xơ.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 180,
                'calo' => 155,
                'thoi_gian_nau' => 5,
                'protein' => 12.5,
                'carb' => 14.0,
                'fat' => 4.5,
                'nguyen_lieu' => "Sữa chua Hy Lạp không đường (150g)\nHạt chia (10g)\nMật ong nguyên chất (1 thìa cà phê)\nQuả việt quất tươi (20g)",
                'huong_dan_nau' => "1. Múc sữa chua Hy Lạp ra cốc.\n2. Rắc hạt chia và quả việt quất lên bề mặt.\n3. Rưới đều mật ong và thưởng thức ngay.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Parfait phô mai tươi & dâu tây',
                'danh_muc_slug' => 'dairy',
                'danh_muc_ten' => 'Sữa và các sản phẩm từ sữa, sữa chua, phô mai cottage',
                'mo_ta' => 'Món tráng miệng ăn kiêng thơm ngon, thanh mát và giàu protein trước buổi tập.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 220,
                'calo' => 195,
                'thoi_gian_nau' => 5,
                'protein' => 16.0,
                'carb' => 21.0,
                'fat' => 3.8,
                'nguyen_lieu' => "Phô mai tươi Cottage Cheese (120g)\nDâu tây tươi cắt lát (80g)\nYến mạch nướng giòn (20g)",
                'huong_dan_nau' => "1. Xếp một lớp phô mai tươi ở đáy ly.\n2. Thêm một lớp dâu tây và yến mạch giòn.\n3. Lặp lại các lớp cho đến khi đầy ly và dùng lạnh.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 2. GRAINS (Ngũ cốc, cháo, khoai) ====================
            [
                'ten_mon_an' => 'Yến mạch nấu sữa hạnh nhân & chuối',
                'danh_muc_slug' => 'grains',
                'danh_muc_ten' => 'Ngũ cốc, cháo, khoai tây chiên',
                'mo_ta' => 'Nguồn carb phức hợp hấp thu chậm kết hợp kali từ chuối giúp duy trì năng lượng bền bỉ.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 250,
                'calo' => 235,
                'thoi_gian_nau' => 10,
                'protein' => 8.5,
                'carb' => 42.0,
                'fat' => 4.2,
                'nguyen_lieu' => "Yến mạch cán dẹt (50g)\nSữa hạnh nhân không đường (180ml)\nChuối chín (1/2 quả)\nBột quế (1/2 thìa cà phê)",
                'huong_dan_nau' => "1. Cho yến mạch và sữa hạnh nhân vào nồi nhỏ đun sôi nhẹ 3-5 phút.\n2. Cắt lát chuối xếp lên trên mặt bát.\n3. Rắc một chút bột quế tạo mùi thơm và thưởng thức ấm.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Khoai lang mật nướng nồi chiên không dầu',
                'danh_muc_slug' => 'grains',
                'danh_muc_ten' => 'Ngũ cốc, cháo, khoai tây chiên',
                'mo_ta' => 'Khoai lang có chỉ số GI thấp, giàu vitamin A và chất xơ hòa tan tốt cho tiêu hóa.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 200,
                'calo' => 172,
                'thoi_gian_nau' => 30,
                'protein' => 3.2,
                'carb' => 39.5,
                'fat' => 0.3,
                'nguyen_lieu' => "Khoai lang mật (200g)\nMuối hạt (1 nhúm nhỏ)",
                'huong_dan_nau' => "1. Rửa sạch khoai lang, ngâm nước muối loãng 10 phút.\n2. Cho khoai vào nồi chiên không dầu nướng 180°C trong 25-30 phút.\n3. Bẻ đôi ăn khi còn nóng mềm ngọt.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Cơm gạo lứt huyết rồng hạt sen',
                'danh_muc_slug' => 'grains',
                'danh_muc_ten' => 'Ngũ cốc, cháo, khoai tây chiên',
                'mo_ta' => 'Gạo lứt giàu vitamin nhóm B và khoáng chất, giúp no lâu và kiểm soát đường huyết.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 180,
                'calo' => 218,
                'thoi_gian_nau' => 45,
                'protein' => 5.8,
                'carb' => 44.0,
                'fat' => 1.8,
                'nguyen_lieu' => "Gạo lứt huyết rồng (70g)\nHạt sen tươi (30g)\nNước lọc (150ml)",
                'huong_dan_nau' => "1. Ngâm gạo lứt trong nước ấm khoảng 2 tiếng trước khi nấu.\n2. Rửa sạch hạt sen, bỏ tâm sen để không bị đắng.\n3. Cho gạo và hạt sen vào nồi cơm điện nấu chín dẻo.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 3. EGGS & CHEESE (Trứng, phô mai) ====================
            [
                'ten_mon_an' => 'Trứng cuộn rau củ phô mai Mozzarella',
                'danh_muc_slug' => 'eggs_cheese',
                'danh_muc_ten' => 'Trứng, phô mai, phô mai chế biến',
                'mo_ta' => 'Bữa sáng nhanh gọn, cung cấp đầy đủ đạm chất lượng cao và chất béo lành mạnh.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 200,
                'calo' => 265,
                'thoi_gian_nau' => 10,
                'protein' => 18.5,
                'carb' => 4.2,
                'fat' => 19.0,
                'nguyen_lieu' => "Trứng gà (2 quả)\nPhô mai Mozzarella bào sợi (25g)\nỚt chuông đỏ (20g)\nHành tây băm nhỏ (15g)\nDầu oliu (5ml)",
                'huong_dan_nau' => "1. Đánh tan trứng cùng chút muối và tiêu.\n2. Xào sơ ớt chuông và hành tây trên chảo chống dính với dầu oliu.\n3. Đổ trứng vào dàn đều, rắc phô mai lên trên rồi cuộn tròn khi trứng vừa chín tới.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Trứng chần lòng đào sốt bơ trái (Avocado Toast)',
                'danh_muc_slug' => 'eggs_cheese',
                'danh_muc_ten' => 'Trứng, phô mai, phô mai chế biến',
                'mo_ta' => 'Sự kết hợp hoàn hảo giữa lòng đỏ trứng béo ngậy và axit béo chưa bão hòa đơn từ bơ.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 190,
                'calo' => 285,
                'thoi_gian_nau' => 8,
                'protein' => 13.2,
                'carb' => 22.0,
                'fat' => 16.5,
                'nguyen_lieu' => "Bánh mì đen nguyên cám (1 lát - 40g)\nTrứng gà (1 quả)\nQuả bơ sáp (50g)\nNước cốt chanh, muối tiêu, ớt bột",
                'huong_dan_nau' => "1. Nghiền nhuyễn thịt bơ với chút nước cốt chanh và muối tiêu.\n2. Nướng giòn bánh mì đen rồi phết bơ lên.\n3. Chần trứng lòng đào trong nước sôi có giấm khoảng 3 phút, vớt ra đặt lên trên bánh mì.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 4. POULTRY (Thịt gà và thịt gia cầm) ====================
            [
                'ten_mon_an' => 'Ức gà áp chảo sốt chanh tây thảo mộc',
                'danh_muc_slug' => 'poultry',
                'danh_muc_ten' => 'Thịt gà và thịt gia cầm khác, thịt gà xay, phụ phẩm',
                'mo_ta' => 'Ức gà mềm mọng nước, ít chất béo bão hòa, chuẩn thực đơn siết cơ giảm mỡ tối ưu.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 250,
                'calo' => 295,
                'thoi_gian_nau' => 15,
                'protein' => 45.0,
                'carb' => 3.5,
                'fat' => 8.2,
                'nguyen_lieu' => "Ức gà phi lê không da (200g)\nNước cốt chanh vàng (1 thìa)\nLá hương thảo (Rosemary)\nTỏi băm, tiêu đen, muối biển, dầu ô liu (5ml)",
                'huong_dan_nau' => "1. Khứa nhẹ bề mặt ức gà, ướp với tỏi, nước chanh, lá hương thảo, muối tiêu trong 15 phút.\n2. Làm nóng chảo với dầu ô liu, áp chảo mỗi mặt 4-5 phút trên lửa vừa.\n3. Đậy vung 2 phút cho thịt ngấm đều và giữ được độ mọng nước.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Salad ức gà xé phay bắp cải tím',
                'danh_muc_slug' => 'poultry',
                'danh_muc_ten' => 'Thịt gà và thịt gia cầm khác, thịt gà xay, phụ phẩm',
                'mo_ta' => 'Món salad giòn mát, thanh lọc cơ thể với lượng calo cực thấp và hàm lượng đạm cao.',
                'anh_dai_dien' => 'https://cdn-i.vtcnews.vn/resize/th/upload/2024/11/27/cach-lam-salad-uc-ga-13193321.png',
                'khoi_luong_gram' => 280,
                'calo' => 240,
                'thoi_gian_nau' => 15,
                'protein' => 35.0,
                'carb' => 12.0,
                'fat' => 4.5,
                'nguyen_lieu' => "Ức gà luộc xé sợi (150g)\nBắp cải tím bào mỏng (80g)\nCà rốt thái sợi (30g)\nRau mùi, nước mắm chanh tỏi ớt ít đường",
                'huong_dan_nau' => "1. Luộc chín ức gà với vài lát gừng, để nguội rồi xé sợi nhỏ.\n2. Trộn đều bắp cải tím, cà rốt và rau mùi.\n3. Rưới nước sốt chanh ớt vào trộn đều và bày ra đĩa.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 5. VEGETABLES (Rau củ, salad) ====================
            [
                'ten_mon_an' => 'Bông cải xanh & măng tây xào tỏi dầu oliu',
                'danh_muc_slug' => 'vegetables',
                'danh_muc_ten' => 'Rau, rau xanh, ô liu',
                'mo_ta' => 'Cung cấp chất xơ prebiotic, sulforaphane chống oxy hóa mạnh mẽ và các vitamin thiết yếu.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 220,
                'calo' => 110,
                'thoi_gian_nau' => 8,
                'protein' => 4.8,
                'carb' => 11.5,
                'fat' => 5.2,
                'nguyen_lieu' => "Bông cải xanh (120g)\nMăng tây tươi (80g)\nTỏi đập dập (3 tép)\nDầu ô liu (5ml)\nMuối biển, tiêu sọ xay",
                'huong_dan_nau' => "1. Cắt nhỏ bông cải và măng tây, chần nhanh qua nước sôi 1 phút rồi vớt ra ngâm nước đá.\n2. Phi thơm tỏi với dầu ô liu trên chảo nóng.\n3. Đổ rau vào xào nhanh lửa lớn trong 2 phút, nêm muối tiêu vừa ăn.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Salad Địa Trung Hải dưa chuột, cà chua & quả ô liu',
                'danh_muc_slug' => 'vegetables',
                'danh_muc_ten' => 'Rau, rau xanh, ô liu',
                'mo_ta' => 'Chế độ ăn Địa Trung Hải trứ danh giúp bảo vệ tim mạch và giảm phản ứng viêm sau tập nặng.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 250,
                'calo' => 145,
                'thoi_gian_nau' => 10,
                'protein' => 3.5,
                'carb' => 14.0,
                'fat' => 8.5,
                'nguyen_lieu' => "Xà lách Romaine (100g)\nCà chua bi (60g)\nDưa chuột giòn (50g)\nQuả ô liu đen (20g)\nDầu ô liu nguyên chất và giấm táo (10ml)",
                'huong_dan_nau' => "1. Rửa sạch rau củ, cắt cà chua bi làm đôi và thái lát dưa chuột.\n2. Cho tất cả vào tô lớn, thêm quả ô liu cắt khoanh.\n3. Rưới dầu ô liu và giấm táo lên, trộn nhẹ tay rồi thưởng thức.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ==================== 6. MEAT & SEAFOOD (Thịt đỏ, cá và hải sản) ====================
            [
                'ten_mon_an' => 'Phi lê cá hồi Nauy áp chảo măng tây',
                'danh_muc_slug' => 'meat_seafood',
                'danh_muc_ten' => 'Thịt đỏ, cá và hải sản',
                'mo_ta' => 'Cá hồi thượng hạng cung cấp Omega-3 EPA/DHA tự nhiên hỗ trợ phục hồi khớp và tăng trưởng cơ nạc.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 260,
                'calo' => 385,
                'thoi_gian_nau' => 12,
                'protein' => 38.5,
                'carb' => 4.0,
                'fat' => 22.0,
                'nguyen_lieu' => "Phi lê cá hồi tươi (180g)\nMăng tây (80g)\nBơ lạt (5g)\nMuối tiêu, lát chanh vàng tươi",
                'huong_dan_nau' => "1. Thấm khô miếng cá hồi, ướp chút muối và tiêu.\n2. Áp chảo mặt da cá trước khoảng 4 phút cho da giòn rụm, sau đó lật mặt thịt áp thêm 2-3 phút.\n3. Xào nhanh măng tây với bơ lạt và dọn ra đĩa cùng cá hồi.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Thịt thăn bò Úc áp chảo tiêu đen',
                'danh_muc_slug' => 'meat_seafood',
                'danh_muc_ten' => 'Thịt đỏ, cá và hải sản',
                'mo_ta' => 'Thịt bò thăn mềm giàu sắt heme, kẽm và Creatine tự nhiên giúp tối ưu hóa sức mạnh cơ bắp.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 240,
                'calo' => 360,
                'thoi_gian_nau' => 10,
                'protein' => 42.0,
                'carb' => 2.0,
                'fat' => 18.5,
                'nguyen_lieu' => "Thịt thăn bò Tenderloin (180g)\nTiêu đen đập dập (1 thìa)\nTỏi (2 tép), lá hương thảo\nDầu ô liu (5ml), muối biển",
                'huong_dan_nau' => "1. Ướp thịt bò với muối biển và tiêu đen đập dập.\n2. Làm nóng chảo gang, áp chảo mỗi mặt 2-3 phút cho độ chín vừa (Medium Rare).\n3. Để thịt nghỉ 3 phút trước khi thái lát mỏng.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_mon_an' => 'Tôm sú hấp sả gừng thanh ngọt',
                'danh_muc_slug' => 'meat_seafood',
                'danh_muc_ten' => 'Thịt đỏ, cá và hải sản',
                'mo_ta' => 'Nguồn protein tinh khiết gần như không chứa chất béo, giàu astaxanthin chống lão hóa.',
                'anh_dai_dien' => 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=800&q=80',
                'khoi_luong_gram' => 250,
                'calo' => 195,
                'thoi_gian_nau' => 10,
                'protein' => 36.0,
                'carb' => 1.5,
                'fat' => 2.2,
                'nguyen_lieu' => "Tôm sú tươi (200g)\nSả tươi đập dập (3 cây)\nGừng thái lát (1 nhánh)\nMuối tiêu chanh chấm kèm",
                'huong_dan_nau' => "1. Rửa sạch tôm, cắt râu và rút chỉ lưng.\n2. Lót sả và gừng dưới đáy nồi hấp, xếp tôm lên trên.\n3. Hấp cách thủy 7-8 phút đến khi tôm chuyển màu đỏ cam đẹp mắt là chín.",
                'tinh_trang' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
